Metrics:
  Enabled: false

Security/Eval:
  Enabled: false

MethodLength:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5.3
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false
